spring.application.name=ProductCrud
springdoc.swagger-ui.path=/docs
spring.datasource.url=jdbc:mysql://localhost:3306/ProductCrud
spring.datasource.username=root
spring.datasource.password=YOUR_PASSWORD

#ddl-auto=update for development - uses existing table, creates new if it is not there
#ddl-auto=none for production - no structural changes the tables allowed
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.format_sql=true